global = [
    { key = "Slash", action = "Search" },
    { key = "T", shift = true, action = "ToggleTheme" },
    { key = "T", ctrl = true, action = "AutomaticTheme" },
    { key = "D", shift = true, action = "ToggleHiddenItems" },
    { key = "R", ctrl = true, action = "ToggleSetting", args = ["RENDER_SILENT_UNREAD"], destinations = ["inbox"] },
    { key = "U", ctrl = true, action = "ToggleSetting", args = ["SORT_BY_UNREAD"], destinations = ["inbox"] },
    { key = "L", ctrl = true, action = "ToggleSetting", args = ["BURY_LOW_PRIORITY"], destinations = ["inbox"] },
    { key = "F", ctrl = true, action = "ToggleSetting", args = ["PIN_FAVORITES"], destinations = ["inbox"] },
]
inbox = [
    { key = "One", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["1"] },
    { key = "Two", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["2"] },
    { key = "Three", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["3"] },
    { key = "Four", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["4"] },
    { key = "Five", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["5"] },
    { key = "Six", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["6"] },
    { key = "Seven", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["7"] },
    { key = "Eight", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["8"] },
    { key = "Nine", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["9"] },
    { key = "One", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["1"] },
    { key = "Two", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["2"] },
    { key = "Three", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["3"] },
    { key = "Four", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["4"] },
    { key = "Five", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["5"] },
    { key = "Six", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["6"] },
    { key = "Seven", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["7"] },
    { key = "Eight", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["8"] },
    { key = "Nine", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["9"] },
    { key = "H", action = "NavigateSpaceRelative", args = ["-1"] },
    { key = "I", action = "NavigateSpaceRelative", args = ["1"] },
    { key = "Zero", action = "SelectSpace", args = ["0"] },
    { key = "Six", action = "SelectSpace", args = ["p:notif"] },
    { key = "Nine", action = "SelectSpace", args = ["@spiritcroc:beeper.com"] },
]
conversation = [
    { key = "G", shift = true, action = "JumpToBottom", chain = true },
    { key = "U", action = "JumpToLastFullyRead" },
    { key = "I", action = "ComposeMessage" },
    { key = "N", ctrl = true, action = "ComposeNotice" },
    { key = "U", ctrl = true, action = "MarkUnread" },
    { key = "M", ctrl = true, action = "MarkRead", chain = true },
    { key = "Enter", action = "ComposerSend" },
    { key = "Enter", ctrl = true, action = "ComposerSend" },
    { key = "Enter", shift = true, action = "ComposerInsertAtCursor", args = ["\n"] },
    { key = "Escape", action = "HideComposerIfEmpty" },
    { key = "T", ctrl = true, action = "ComposerInsertAtCursor", args = ["ü§î"] },
    { key = "J", ctrl = true, action = "ComposerInsertAtCursor", args = ["üòÇ"] },
    { key = "R", ctrl = true, action = "ComposerInsertAtCursor", args = ["ü§£"] },
    { key = "H", ctrl = true, action = "ComposerInsertAtCursor", args = ["‚ù§Ô∏è"] },
    { key = "U", ctrl = true, action = "ComposerInsertAtCursor", args = ["üëç"] },
    { key = "D", ctrl = true, action = "ComposerInsertAtCursor", args = ["üôÉ"] },
    { key = "Y", ctrl = true, action = "ComposerInsertAtCursor", args = ["üëÄ"] },
    { key = "X", ctrl = true, action = "ComposerInsertAtCursor", args = ["üòÜ"] },
]
event = [
    { key = "M", action = "MarkRead" },
    { key = "R", ctrl = true, action = "ComposeReply" },
    { key = "C", action = "ComposeReaction" },
    { key = "E", ctrl = true, action = "ComposeEdit" },
    { key = "Y", action = "CopyContent" },
    { key = "Y", shift = true, action = "CopyEventSource" },
    { key = "Y", ctrl = true, action = "CopyEventId" },
    { key = "Y", ctrl = true, shift = true, action = "CopyMxId" },
]
navigation = [
    { key = "I", shift = true, action = "NavigateCurrent", args = ["inbox"] },
    { key = "I", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["inbox"] },
    { key = "A", shift = true, action = "NavigateCurrent", args = ["accounts"] },
    { key = "A", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["accounts"] },
    { key = "S", shift = true, action = "SplitHorizontal" },
    { key = "V", shift = true, action = "SplitVertical" },
    { key = "Q", ctrl = true, action = "CloseWindow" },
    { key = "Q", action = "CloseWindow", destinations = ["Conversation"] },
    { key = "M", ctrl = true, action = "CloseWindow", destinations = ["Conversation"] },
]
navigationItem = [
    { key = "Enter", action = "NavigateInNewWindow" },
    { key = "Enter", shift = true, action = "NavigateCurrent" },
]
focus = [
    { key = "DirectionUp", action = "FocusUp" },
    { key = "DirectionDown", action = "FocusDown" },
    { key = "DirectionLeft", action = "FocusLeft" },
    { key = "DirectionRight", action = "FocusRight" },
    { key = "K", action = "FocusUp" },
    { key = "J", action = "FocusDown" },
    { key = "E", action = "FocusUp" },
    { key = "N", action = "FocusDown" },
    { key = "H", shift = true, action = "FocusTop" },
    { key = "M", shift = true, action = "FocusCenter" },
    { key = "L", shift = true, action = "FocusBottom" },
    { key = "Escape", action = "FocusParent" },
    { key = "Enter", action = "FocusEnterContainer" },
    { key = "MoveHome", action = "FocusTop" },
    { key = "MoveEnd", action = "FocusBottom" },
]
list = [
    { key = "G", action = "ScrollToStart" },
    { key = "G", shift = true, action = "ScrollToBottom" },
]
split = [
    { key = "Q", shift = true, action = "Close" },
]
