global = [
    { key = "Slash", action = "Search" },
    { key = "T", shift = true, action = "ToggleTheme" },
    { key = "T", ctrl = true, action = "AutomaticTheme" },
    { key = "D", shift = true, action = "ToggleHiddenItems" },
]
inbox = [
    { key = "R", ctrl = true, action = "ToggleSetting", args = ["RENDER_SILENT_UNREAD"] },
    { key = "U", ctrl = true, action = "ToggleSetting", args = ["SORT_BY_UNREAD"] },
    { key = "L", ctrl = true, action = "ToggleSetting", args = ["BURY_LOW_PRIORITY"] },
    { key = "F", ctrl = true, action = "ToggleSetting", args = ["PIN_FAVORITES"] },
    { key = "One", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["1"] },
    { key = "Two", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["2"] },
    { key = "Three", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["3"] },
    { key = "Four", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["4"] },
    { key = "Five", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["5"] },
    { key = "Six", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["6"] },
    { key = "Seven", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["7"] },
    { key = "Eight", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["8"] },
    { key = "Nine", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["9"] },
    { key = "One", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["1"] },
    { key = "Two", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["2"] },
    { key = "Three", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["3"] },
    { key = "Four", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["4"] },
    { key = "Five", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["5"] },
    { key = "Six", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["6"] },
    { key = "Seven", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["7"] },
    { key = "Eight", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["8"] },
    { key = "Nine", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["9"] },
]
conversation = [
    { key = "I", ctrl = true, action = "ComposeMessage" },
    { key = "N", ctrl = true, action = "ComposeNotice" },
    { key = "M", ctrl = true, action = "ComposeEmote" },
    { key = "Enter", ctrl = true, action = "ComposerSend" },
    { key = "Escape", action = "HideComposerIfEmpty" },
]
event = [
    { key = "M", action = "MarkRead" },
    { key = "M", ctrl = true, action = "MarkReadPrivate" },
    { key = "R", ctrl = true, action = "ComposeReply" },
    { key = "E", ctrl = true, action = "ComposeEdit" },
    { key = "Y", action = "CopyContent" },
    { key = "Y", shift = true, action = "CopyEventSource" },
]
navigation = [
    { key = "I", shift = true, action = "InboxInCurrent" },
    { key = "I", shift = true, ctrl = true, action = "InboxInNewWindow" },
    { key = "A", shift = true, action = "AccountManagementInCurrent" },
    { key = "A", shift = true, ctrl = true, action = "AccountManagementInNewWindow" },
    { key = "S", shift = true, action = "SplitHorizontal" },
    { key = "V", shift = true, action = "SplitVertical" },
]
navigationItem = [
    { key = "Enter", action = "NavigateCurrent" },
    { key = "Enter", shift = true, action = "NavigateInNewWindow" },
]
focus = [
    { key = "DirectionUp", action = "FocusUp" },
    { key = "DirectionDown", action = "FocusDown" },
    { key = "DirectionLeft", action = "FocusLeft" },
    { key = "DirectionRight", action = "FocusRight" },
    { key = "K", action = "FocusUp" },
    { key = "J", action = "FocusDown" },
    { key = "H", action = "FocusLeft" },
    { key = "L", action = "FocusRight" },
    { key = "E", action = "FocusUp" },
    { key = "N", action = "FocusDown" },
    { key = "I", action = "FocusRight" },
    { key = "H", shift = true, action = "FocusTop" },
    { key = "M", shift = true, action = "FocusCenter" },
    { key = "L", shift = true, action = "FocusBottom" },
    { key = "Escape", action = "FocusParent" },
    { key = "MoveHome", action = "FocusTop" },
    { key = "MoveEnd", action = "FocusBottom" },
]
list = [
    { key = "G", action = "ScrollToTop" },
    { key = "G", shift = true, action = "ScrollToBottom" },
]
split = [
    { key = "Q", shift = true, action = "Close" },
]
