global = [
    { key = "Slash", action = "Search" },
    { key = "Semicolon", action = "Command" },
    { key = "T", shift = true, action = "SetSetting", args = ["THEME_FOLLOW_SYSTEM", "false"], chain = true },
    { key = "T", shift = true, action = "ToggleSetting", args = ["THEME_DARK"] },
    { key = "T", ctrl = true, action = "SetSetting", args = ["THEME_FOLLOW_SYSTEM", "true"] },
    { key = "S", ctrl = true, shift = true, action = "ToggleSetting", args = ["RENDER_SCALE", "1.8", "1.0"] },
    { key = "U", ctrl = true, action = "ToggleSetting", args = ["SORT_BY_UNREAD"], destinations = ["Inbox"] },
    { key = "L", ctrl = true, action = "ToggleSetting", args = ["BURY_LOW_PRIORITY"], destinations = ["Inbox"] },
    { key = "F", ctrl = true, action = "ToggleSetting", args = ["PIN_FAVORITES"], destinations = ["Inbox"] },
    { key = "H", ctrl = true, action = "ToggleSetting", args = ["VIEW_HIDDEN_EVENTS"], destinations = ["Conversation"] },
    { key = "K", ctrl = true, action = "ToggleSetting", args = ["MINIMAL_MODE"] },
    { key = "X", ctrl = true, shift = true, action = "Exit" },
    { key = "R", ctrl = true, action = "RecreateWindow" },
    { key = "R", ctrl = true, shift = true, action = "RecreateUi" },
]
appMessage = [
    { key = "Escape", action = "ClearAppMessages" },
    { key = "Enter", action = "ConfirmActionAppMessage" },
]
inbox = [
    { key = "One", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["1"] },
    { key = "Two", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["2"] },
    { key = "Three", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["3"] },
    { key = "Four", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["4"] },
    { key = "Five", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["5"] },
    { key = "Six", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["6"] },
    { key = "Seven", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["7"] },
    { key = "Eight", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["8"] },
    { key = "Nine", ctrl = true, action = "ToggleAccountExclusivelySelected", args = ["9"] },
    { key = "One", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["1"] },
    { key = "Two", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["2"] },
    { key = "Three", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["3"] },
    { key = "Four", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["4"] },
    { key = "Five", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["5"] },
    { key = "Six", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["6"] },
    { key = "Seven", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["7"] },
    { key = "Eight", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["8"] },
    { key = "Nine", ctrl = true, shift = true, action = "ToggleAccountSelected", args = ["9"] },
    { key = "H", action = "NavigateSpaceRelative", args = ["-1"] },
    { key = "I", action = "NavigateSpaceRelative", args = ["1"] },
    { key = "Zero", action = "SelectSpace", args = ["0"] },
    { key = "Equals", shift = true, action = "SelectSpace", args = ["p:notif"] },
]
room = [
    { key = "M", ctrl = true, action = "MarkRoomRead", destinations = ["Inbox"] },
]
conversation = [
    { key = "G", shift = true, action = "JumpToBottom", chain = true },
    { key = "U", action = "JumpToFullyRead" },
    { key = "U", shift = true, action = "JumpToOwnReadReceipt" },
    { key = "I", action = "FocusComposer" },
    { key = "P", action = "ComposerPasteText" },
    { key = "I", ctrl = true, action = "ComposeMessage" },
    { key = "V", ctrl = true, action = "ComposerPasteAttachment" },
    { key = "N", ctrl = true, action = "ComposeNotice" },
    { key = "E", ctrl = true, shift = true, action = "ComposeEmote" },
    { key = "M", ctrl = true, shift = true, action = "MarkReadPrivate", chain = true },
    { key = "M", ctrl = true, shift = true, action = "MarkFullyRead", chain = true },
    { key = "F", alt = true, action = "MarkRead", chain = true },
    { key = "F", alt = true, action = "MarkFullyRead", chain = true },
    { key = "M", ctrl = true, action = "MarkRead", chain = true },
    { key = "M", ctrl = true, action = "MarkFullyRead" },
    { key = "Enter", action = "ComposerSuggestionApplySelected" },
    { key = "Enter", action = "ComposerSend" },
    { key = "Enter", ctrl = true, action = "ComposerSend" },
    { key = "Enter", shift = true, action = "ComposerInsertAtCursor", args = ["\n"] },
    { key = "Escape", action = "HideComposerIfEmpty" },
    { key = "O", ctrl = true, action = "ClearComposer" },
    { key = "D", ctrl = true, action = "ClearComposer" },
    { key = "Tab", action = "ComposerSuggestionFocusNext" },
    { key = "Tab", shift = true, action = "ComposerSuggestionFocusPrevious" },
]
event = [
    { key = "M", action = "MarkRead", chain = true },
    { key = "M", action = "MarkFullyRead", chain = true },
    { key = "R", action = "ComposeReply" },
    { key = "C", action = "ComposeReaction" },
    { key = "Semicolon", shift = true, action = "ComposeReaction" },
    { key = "E", ctrl = true, action = "ComposeEdit" },
    { key = "Y", action = "CopyContent" },
    { key = "Y", shift = true, action = "CopyEventSource" },
    { key = "Y", ctrl = true, action = "CopyEventId" },
    { key = "Y", ctrl = true, shift = true, action = "CopyFormattedBody" },
    { key = "Y", alt = true, action = "CopyMxId" },
    { key = "Y", alt = true, shift = true, action = "CopyMxc" },
    { key = "B", action = "OpenContentLinks" },
    { key = "B", ctrl = true, action = "CopyContentLink" },
    { key = "D", action = "Redact" },
    { key = "Delete", action = "Redact" },
    { key = "Backspace", action = "Redact" },
    { key = "Enter", action = "DownloadFileAndOpen" },
    { key = "One", ctrl = true, action = "ToggleReactionIndex", args = ["0"] },
    { key = "Two", ctrl = true, action = "ToggleReactionIndex", args = ["1"] },
    { key = "Three", ctrl = true, action = "ToggleReactionIndex", args = ["2"] },
    { key = "Four", ctrl = true, action = "ToggleReactionIndex", args = ["3"] },
    { key = "Five", ctrl = true, action = "ToggleReactionIndex", args = ["4"] },
    { key = "Six", ctrl = true, action = "ToggleReactionIndex", args = ["5"] },
]
navigation = [
    { key = "I", shift = true, action = "NavigateCurrent", args = ["inbox"] },
    { key = "I", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["inbox"] },
    { key = "A", shift = true, action = "NavigateCurrent", args = ["accounts"] },
    { key = "A", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["accounts"] },
    { key = "S", shift = true, action = "NavigateCurrent", args = ["settings"] },
    { key = "S", shift = true, ctrl = true, action = "NavigateInNewWindow", args = ["settings"] },
    { key = "X", action = "CloseWindowUnlessLast" },
    { key = "X", action = "NavigateCurrent", args = ["inbox"] },
    { key = "F", alt = true, action = "CloseWindowUnlessLast", destinations = ["Conversation"] },
    { key = "F", alt = true, action = "NavigateCurrent", args = ["inbox"] },
]
navigationItem = [
    { key = "Enter", action = "NavigateInNewWindow" },
    { key = "Enter", shift = true, action = "NavigateCurrent" },
]
focus = [
    { key = "Enter", ctrl = true, action = "OpenContextMenu" },
    { key = "DirectionUp", action = "FocusUp" },
    { key = "DirectionDown", action = "FocusDown" },
    { key = "DirectionLeft", action = "FocusLeft" },
    { key = "DirectionRight", action = "FocusRight" },
    { key = "E", action = "FocusUp" },
    { key = "N", action = "FocusDown" },
    { key = "H", shift = true, action = "FocusTop" },
    { key = "M", shift = true, action = "FocusCenter" },
    { key = "L", shift = true, action = "FocusBottom" },
    { key = "Escape", shift = true, action = "FocusParent" },
    { key = "Enter", action = "FocusEnterContainer" },
    { key = "MoveHome", action = "FocusTop" },
    { key = "MoveEnd", action = "FocusBottom" },
]
list = [
    { key = "G", action = "ScrollToStart" },
    { key = "G", shift = true, action = "ScrollToBottom" },
]
split = [
    { key = "Q", ctrl = true, action = "Unsplit" },
]
